name: Run Python and Send Errors

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run main.py and capture error
        id: run_script
        continue-on-error: true
        run: |
          python main.py 2> error.txt

      - name: Send to Zapier now 
        run: |
          ERROR=$(cat error.txt)
          echo "Sending ERROR: $ERROR"
          curl -v -X POST https://hooks.zapier.com/hooks/catch/26934524/upv6b48/ \
          -H "Content-Type: application/json" \
          -d "{\"error\": \"$ERROR\"}"
